version: "3.0"

services:
  broker-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: broker-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${HOME}/volumes/dev-rabbitmq/data:/var/lib/rabbitmq
    restart: always
  redis-db:
    image: redis:6-alpine
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${HOME}/volumes/redis-db/data:/data
volumes:
  logs:
    name: log-rabbitmq
    driver: local